# config-management.yaml
apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  policyController:
    enabled: true
  clusterName: attached-anthos
  enableMultiRepo: true
  # the `preventDrift` field is supported in Anthos Config Management version 1.10.0 and later.
  preventDrift: false
