apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springstore-dev
  namespace: argocd
spec:
  destination:
    namespace: springstore-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kube/dev/
    repoURL: git@gitlab.com:daniyalj/spring-store-env.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
  sourceType: Directory
  sync:
    comparedTo:
      destination:
        namespace: springstore-dev
        server: https://kubernetes.default.svc
      source:
        path: kube/dev/
        repoURL: git@gitlab.com:daniyalj/spring-store-env.git
        targetRevision: master
